# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cukepatch}
  s.version = "0.2.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Joseph Wilk"]
  s.date = %q{2010-09-14}
  s.description = %q{Run tests priorited by those that are most likely to fail}
  s.email = %q{joe@josephwilk.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION.yml",
     "cucumber.yml",
     "cukepatch.gemspec",
     "examples/self_test/.gitignore",
     "features/auto_configure.feature",
     "features/multiple_projects.feature",
     "features/rake_task.feature",
     "features/run_tests_that_matter.feature",
     "features/running_cucumber_without_recording.feature",
     "features/running_subset_of_features.feature",
     "features/step_definitions/cucumber_steps.rb",
     "features/step_definitions/cuke_max_steps.rb",
     "features/step_definitions/cukepatch_steps.rb",
     "features/step_definitions/feature_steps.rb",
     "features/support/env.rb",
     "features/support/hooks.rb",
     "lib/cukepatch.rb",
     "lib/cukepatch/config.rb",
     "lib/cukepatch/feature.rb",
     "lib/cukepatch/formatter/stats.rb",
     "lib/cukepatch/gzip.rb",
     "lib/cukepatch/plugin.rb",
     "lib/cukepatch/stats.rb",
     "lib/cukepatch/thread_pool.rb",
     "spec/spec_helper.rb",
     "tasks/cucumber.rake",
     "tasks/rspec.rake",
     "tasks/services.rake"
  ]
  s.homepage = %q{http://www.josephwilk.net}
  s.post_install_message = %q{}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Run tests priorited by those that are most likely to fail}
  s.test_files = [
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, ["= 0.5.2"])
      s.add_runtime_dependency(%q<cucumber>, [">= 0.8.0"])
    else
      s.add_dependency(%q<httparty>, ["= 0.5.2"])
      s.add_dependency(%q<cucumber>, [">= 0.8.0"])
    end
  else
    s.add_dependency(%q<httparty>, ["= 0.5.2"])
    s.add_dependency(%q<cucumber>, [">= 0.8.0"])
  end
end

